# Generated by Django 6.1 on 2026-08-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('deadline_time', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('web_name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('ownership', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['web_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('expected_goals', models.FloatField(default=0)),
                ('expected_assists', models.FloatField(default=0)),
                ('expected_goal_involvements', models.FloatField(default=0)),
                ('expected_goals_conceded', models.FloatField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='fpl.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fpl.team'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kickoff_time', models.DateTimeField(blank=True, null=True)),
                ('home_difficulty', models.IntegerField(blank=True, null=True)),
                ('away_difficulty', models.IntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fpl.gameweek')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fpl.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fpl.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameweekStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('expected_goals', models.FloatField(default=0)),
                ('expected_assists', models.FloatField(default=0)),
                ('expected_goal_involvements', models.FloatField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='fpl.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='fpl.player')),
            ],
            options={
                'ordering': ['gameweek', 'player'],
                'constraints': [models.UniqueConstraint(fields=('player', 'gameweek'), name='unique_player_gameweek')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_points', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='baseline-v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fpl.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fpl.player')),
            ],
            options={
                'ordering': ['-predicted_points'],
                'constraints': [models.UniqueConstraint(fields=('player', 'gameweek', 'model_version'), name='unique_prediction_version')],
            },
        ),
    ]
