# Generated by Django 6.1 on 2026-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['kickoff_time']},
        ),
        migrations.AlterModelOptions(
            name='playerseasonstats',
            options={'ordering': ['-expected_goal_involvements']},
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_assists',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goal_involvements',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='expected_goals_conceded',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='form',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='points_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='starts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
